# Generated by Django 2.1.7 on 2019-03-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workSheetTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='优先级')),
                ('order_id', models.IntegerField(verbose_name='序号ID')),
                ('order_time', models.DateField(verbose_name='提出时间')),
                ('topic_type', models.CharField(choices=[('D', '需求'), ('B', '问题'), ('P', '疑问')], default='D', max_length=10, verbose_name='类型')),
                ('topic_desc', models.CharField(max_length=1000, verbose_name='备注')),
                ('dev_person', models.CharField(max_length=16, verbose_name='开发人员')),
                ('dev_state', models.CharField(choices=[('U', '未开发'), ('I', '开发中'), ('D', '开发完成'), ('A', '待分析')], max_length=10, verbose_name='开发状态')),
                ('plan_dev_finish_time', models.DateField(verbose_name='计划开发完成时间')),
                ('dev_finish_time', models.DateField(verbose_name='实际开发完成时间')),
                ('test_person', models.CharField(max_length=16, verbose_name='测试人员')),
                ('test_state', models.CharField(choices=[('U', '未测试'), ('I', '测试中'), ('D', '测试完成')], max_length=16, verbose_name='测试状态')),
                ('plan_test_finish_time', models.DateField(verbose_name='计划测试完成时间')),
                ('test_finish_time', models.DateField(verbose_name='实际测试完成时间')),
                ('plan_online_time', models.DateField(verbose_name='计划上线时间')),
            ],
        ),
    ]
